// packages/react/src/index.ts
import { useSyncExternalStore, useEffect, useRef, useCallback } from 'react';
import type { EventiqEngine, EventiqState, ExecutionOutcome } from '@eventiq/core';

export function useEventiqState<TPlanName extends string, TStepName extends string>(
  engine: EventiqEngine<TPlanName, TStepName>,
): EventiqState<TPlanName, TStepName> {
  return useSyncExternalStore(
    (cb) => engine.subscribe(cb),
    () => engine.getState(),
  );
}

export function useStepStarted<TPlanName extends string, TStepName extends string>(
  engine: EventiqEngine<TPlanName, TStepName>,
  name: TStepName,
  callback: () => void,
): void {
  const ref = useRef(callback);
  ref.current = callback;

  useEffect(() => {
    return engine.onStepStarted(name, () => ref.current());
  }, [engine, name]);
}

export function useStepCompleted<TPlanName extends string, TStepName extends string>(
  engine: EventiqEngine<TPlanName, TStepName>,
  name: TStepName,
  callback: (outcome: ExecutionOutcome) => void,
): void {
  const ref = useRef(callback);
  ref.current = callback;

  useEffect(() => {
    return engine.onStepCompleted(name, (outcome) => ref.current(outcome));
  }, [engine, name]);
}

export function useStepsReady<TPlanName extends string, TStepName extends string>(
  engine: EventiqEngine<TPlanName, TStepName>,
  callback: (names: TStepName[]) => void,
): void {
  const ref = useRef(callback);
  ref.current = callback;

  useEffect(() => {
    return engine.onStepsReady((names) => ref.current(names));
  }, [engine]);
}

export function useAutoSchedule<TPlanName extends string, TStepName extends string>(
  engine: EventiqEngine<TPlanName, TStepName>,
): void {
  useEffect(() => {
    return engine.onStepsReady((names) => {
      for (const name of names) engine.start(name);
    });
  }, [engine]);
}

// packages/angular/src/index.ts
import { Injectable, OnDestroy } from '@angular/core';
import { Observable, BehaviorSubject, Subject } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import type { EventiqEngine, EventiqState, ExecutionOutcome } from '@eventiq/core';

@Injectable()
export class EventiqService<TPlanName extends string, TStepName extends string> implements OnDestroy {
  private engine!: EventiqEngine<TPlanName, TStepName>;
  private state$ = new BehaviorSubject<EventiqState<TPlanName, TStepName>>({ queue: [] });
  private stepsReady$ = new Subject<TStepName[]>();
  private stepStarted$ = new Subject<TStepName>();
  private stepCompleted$ = new Subject<{ name: TStepName; outcome: ExecutionOutcome }>();
  private unsubscribes: (() => void)[] = [];

  init(engine: EventiqEngine<TPlanName, TStepName>): void {
    this.engine = engine;
    this.state$.next(engine.getState());

    this.unsubscribes.push(
      engine.subscribe(() => this.state$.next(engine.getState())),
      engine.onStepsReady((names) => this.stepsReady$.next(names)),
    );
  }

  getState(): Observable<EventiqState<TPlanName, TStepName>> {
    return this.state$.asObservable();
  }

  getStepsReady(): Observable<TStepName[]> {
    return this.stepsReady$.asObservable();
  }

  onStepStarted(name: TStepName): Observable<void> {
    return this.stepStarted$.pipe(
      filter((n) => n === name),
      map(() => undefined),
    );
  }

  onStepCompleted(name: TStepName): Observable<ExecutionOutcome> {
    return this.stepCompleted$.pipe(
      filter((e) => e.name === name),
      map((e) => e.outcome),
    );
  }

  submit(plan: Parameters<EventiqEngine<TPlanName, TStepName>['submit']>[0]): void {
    this.engine.submit(plan);
  }

  start(name: TStepName): void {
    this.engine.start(name);
    this.stepStarted$.next(name);
  }

  complete(name: TStepName, outcome: ExecutionOutcome): void {
    this.engine.complete(name, outcome);
    this.stepCompleted$.next({ name, outcome });
  }

  ngOnDestroy(): void {
    for (const unsub of this.unsubscribes) unsub();
    this.state$.complete();
    this.stepsReady$.complete();
    this.stepStarted$.complete();
    this.stepCompleted$.complete();
  }
}
